### PR TITLE
Divide into parts. Add stanza to part 2. Add part 3. Amend mistakes i…

### PR DESCRIPTION
**Pull request by morosebose**
…n rest of lyrics. Add year and credits. Clean up iTrans, spelling, and format.

### CODE REVIEW

**Comment by morosebose** [comment]
Uday Patel submitted one stanza (faaqo.n kii chitaao.n par) for FITB and I added Part 3 but never got around to posting the installment on RMIM. Aniket Sule commented on the existing version of the song on giitaayan including one missing line in the sthaayi. Lots of mistakes in the lyrics as currently in the ISB.

**Comment by v9y** [comment]
> I've made the changes. Before I push, I wanted your opinion on one point, and to alert you to a couple other things.
> 
> * I'm leaning toward changing "apane kaale" to "apanii kaalii". Mukesh's pronunciation of "apane" is ambiguous, it could easily be apanii. The "kaale" does sound clearly like "kaale" to me, but I would still want to keep it grammatical. And he also clearly says "maanaa ke" where grammatically it should be "maanaa ki". So if we're changing the latter to be grammatical, why not change the former as well?

True, but I don't think it's Mukesh. It's Sahir. karatuut seems to be one of those few words which have different genders in Hindi versus Urdu. In Hindi, it is feminine. But in Urdu, it seems to have been used as masculine. Here's a couple of other examples:
degaa mere karatoot kaa taawaan koii aur 
hai jurm meraa, hogaa pashemaan koii aur

hai ba.Daa jigaraa tiraa inshaa are tuu qahar hai
kab talk mai.n tere karatuuto.n ko rakkhuu.N Dhaa.Np-Dhaa.Np

**Comment by morosebose** [comment]
OIC, like "saa.Ns": `jo saa.Ns aa rahaa hai kisiikaa payaam hai`. Okie, you (or Sahir, or Mukesh) win. `kaale` it is. I'll push shortly.

**Comment by morosebose** [comment]
k, new commit pushed. Phew, this turned out to be a lot of work 🙃

**Comment by v9y** [comment]
Merged. BTW, I had invited you for the collaborator role. It is still pending your acceptance. Here again: https://github.com/v9y/giit/invitations

**Pull request merged**
