### PR TITLE
Add stars and credits. Add missing stanza. Correct errors.

### PR DESCRIPTION
**Pull request by morosebose**

### CODE REVIEW

**Comment by morosebose** [comment]
'sup yo. Figured that just as in the pre-GitHub days I'd send you fresh files even when you had updates pending, 'tis okay to have multiple branches waiting on your review. Lemme know if you prefer to have just one pull request waiting at a time. Another one from the FITB archives, courtesy Uday Patel. I wonder what happened to Uday, I've completely lost touch with him.

**Comment by v9y** [comment]
It's fine to send multiple PRs but I think you should also be able to push additional commits to the same branch (after it has been sent for PR) until it is reviewed.

**Comment by morosebose** [comment]
Yeah, I've used multiple commits to correct mistakes that I've spotted after issuing a PR for a given song.  But for different songs, I think it's cleaner to leave each song in its own PR rather than have two-three different commits with different songs in the same PR. Would you agree?

**Comment by v9y** [comment]
Yes, that's better.

**Pull request merged**
