### PR TITLE
1864: vo subah kabhii to aaegii

### PR DESCRIPTION
**Pull request by morosebose**
- Add verse to Part 3

### CODE REVIEW

**Comment by morosebose** [comment]
gawd, will we never be done with this song

**Comment by v9y** [comment]
That 'duniyaa agar aur...' sounds like a weird construction. Can this be listened to somewhere?

**Comment by morosebose** [comment]
> That 'duniyaa agar aur...' sounds like a weird construction. Can this be listened to somewhere?

Not that I have heard so far. It's another one from the cheaply printed song book, like the last verse of "hamasafar saath". I agree, it's weird, even when agar is treated as in agar_battii

**Comment by morosebose** [comment]
Cool! Thanks for tracking that down. The film version definitely has the "jelo.n ke binaa" line where the earlier commits had it, though. I guess it's a question of whether we want to have the to.D-mo.D filmi version or the Sahir version. I'd go with the latter myself (i.e., as you have it now), but it's up to you.

**Pull request merged**
